name: GitHub Metrics
on:
#   schedule: [{cron: "15,45 * * * *"}]
  workflow_dispatch:
#   push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Pacific/Auckland

          user: apteryxxyz
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # introduction
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # languages
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 0
          
          # spotify music
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_ID }}, ${{ secrets.SPOTIFY_SECRET }}, ${{ secrets.SPOTIFY_TOKEN }}"
          plugin_music_mode: recent
          plugin_music_limit: 5
          
          # habits
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 100
          
          # stars
          plugin_stars: yes
          plugin_stars_limit: 4
